version: "1.0"

services:
  web:
    build: .
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/health"] # Replace /health with your health endpoint.
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
